name: Deploy Jekyll Site
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec jekyll build --base "${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
    - uses: actions/upload-pages-artifact@v3
      with:
        path: './_site'

  deploy:  
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v4